[package]
name = "raptors-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "raptors_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2"
bitflags = "2.10"

[build-dependencies]
cbindgen = "0.29"

[dev-dependencies]
cc = "1.0"
